name: run-docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:

  compile:
    runs-on: ubuntu-latest
    
    steps:
    - name: Login to Dockerhub
      run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Pull the Docker image
      run: docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/nodejs-app 
    - name: Run the Docker image
      run: docker run -d -p 80:80 ${{ secrets.DOCKER_HUB_USERNAME }}/nodejs-app nginx -g 'daemon off;' 
    - name: test
      run: docker ps
        
