name: main-workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:

  run-linters:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          DEFAULT_BRANCH: master
          
  docker:
    runs-on: ubuntu-latest
    needs: [run-linters]

    steps:
      -
        name: Checkout Code
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nodejs-app:latest

  compile:
    runs-on: ubuntu-latest
    needs: [run-linters, docker]
    
    steps:
    - name: Login to Dockerhub
      run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Pull the Docker image
      run: docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/nodejs-app 
    - name: Run the Docker image
      run: docker run -d -p 80:80 ${{ secrets.DOCKER_HUB_USERNAME }}/nodejs-app
    - name: curl
      run: |
        sleep 5
        curl http://localhost:80
      
  
    
    
